version: '3.2'

services:
  alfresco:
    environment:
      - INDEX=solr6
  solr:
     image: hub.xenit.eu/public/alfresco-solr6-xenit:2.0.1
     environment:
       - ALFRESCO_SSL=none
     ports:
      - target: 8080
        mode: host

