version: '3.2'

services:
  alfresco:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-repository-enterprise-xenit:6.2.0  
    environment:
      - INDEX=solr6
      - SOLR_SSL=none
      - ENABLE_CLUSTERING=true
      - DYNAMIC_SHARD_REGISTRATION=true
      - GLOBAL_metrics.enabled=true
      - GLOBAL_alfred.telemetry.alfresco-integration.enabled=true
      # Expose AT metrics in the Alfresco endpoint:
      - GLOBAL_alfred.telemetry.alfresco-integration.use-default-alfresco-registry=true
      # Enable Care4Alf metrics:
      - GLOBAL_alfred.telemetry.binder.care4alf.enabled=true
      # Enable Alfresco cache metrics:
      - GLOBAL_alfred.telemetry.binder.cache.enabled=true
      # Disable transformers
      - GLOBAL_local.transform.service.enabled=false
      - GLOBAL_legacy.transform.service.enabled=false
      - GLOBAL_jodconverter.enabled=false      
  shard1:
    image: hub.xenit.eu/public/alfresco-solr6-xenit:2.0.1
    container_name: shard1
    ports:
      - 8081:8080
    hostname: shard1
    environment:
    - JAVA_XMX=1024M 
    - SOLR_HOST=shard1
    - ALFRESCO_SSL=none
    - CORES_TO_TRACK=alfresco
    - CORES_ALFRESCO=shard1
    - GLOBAL_ALL_shard.method=DB_ID
    - GLOBAL_ALL_shard.count=2
    - GLOBAL_shard1_shard.instance=0
  
  shard2:
    image: hub.xenit.eu/public/alfresco-solr6-xenit:2.0.1
    container_name: shard2
    ports:
      - 8082:8080
    hostname: shard2
    environment:
      - JAVA_XMX=1024M 
      - SOLR_HOST=shard2
      - ALFRESCO_SSL=none
      - CORES_TO_TRACK=alfresco
      - CORES_ALFRESCO=shard2
      - GLOBAL_ALL_shard.method=DB_ID
      - GLOBAL_ALL_shard.count=2
      - GLOBAL_shard2_shard.instance=1

  postgresql:
    image: docker.io/xenit/postgres
    environment:
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfresco