version: '3.2'

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.27.1
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: docker.io/grafana/grafana:7.5.7
    volumes:
    - ./prometheus/grafana/prometheus-datasources.yml:/etc/grafana/provisioning/datasources/prometheus-datasources.yml:ro
    - ./prometheus/grafana/prometheus-dashboards.yml:/etc/grafana/provisioning/dashboards/prometheus-dashboards.yml:ro
    - ./prometheus/grafana/dashboards:/etc/grafana/provisioning/dashboards/prometheus:ro
    ports:
    - 3000:3000  


volumes:
  prometheus_data:
