version: '3.2'

services:
  alfresco:
    image: ${DOCKER_ACS_DOCKER_IMAGE}
    ports:
      - target: 8080
        mode: host
        published: 8080
    #      - target: 8000
    #       mode: host
    #       published: 8000
    #     - target: 5000
    #       mode: host
    #       published: 5000
    environment:
      - DEBUG=true
      - JMX_ENABLED=true
      - INDEX=noindex
      - ENABLE_CLUSTERING=true
      - GLOBAL_metrics.enabled=true
      - GLOBAL_alfred.telemetry.alfresco-integration.enabled=true
      # Expose AT metrics in the Alfresco endpoint:
      - GLOBAL_alfred.telemetry.alfresco-integration.use-default-alfresco-registry=true
      # Enable Care4Alf metrics:
      - GLOBAL_alfred.telemetry.binder.care4alf.enabled=true
      # Enable Alfresco cache metrics:
      - GLOBAL_alfred.telemetry.binder.cache.enabled=true
      # Disable transformers
      - GLOBAL_local.transform.service.enabled=false
      - GLOBAL_legacy.transform.service.enabled=false
      - GLOBAL_jodconverter.enabled=false
      # Alfresco Health Processor configuration
#      - GLOBAL_eu.xenit.alfresco.healthprocessor.task.cron=0/30 * * * * ? *
#      - GLOBAL_eu.xenit.alfresco.healthprocessor.processing.node-batch-size=10
#      - GLOBAL_eu.xenit.alfresco.healthprocessor.processing.max-batches-per-second=10
      - GLOBAL_eu.xenit.alfresco.healthprocessor.reporter.alfred-telemetry.enabled=true
      - GLOBAL_eu.xenit.alfresco.healthprocessor.reporter.log.summary.enabled=true
      - GLOBAL_eu.xenit.alfresco.healthprocessor.plugin.content-validation.enabled=true

  #  share:
  #   image: docker.io/xenit/alfresco-share-community:5.2.f
  #   ports:
  #    - target: 8080
  #      mode: host

  postgresql:
    image: docker.io/xenit/postgres
    environment:
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfresco
