{
 "title": "Solr (Alfred Telemetry)",
 "description": "Dashboard for Solr based on metrics collected by PrometheusHandler",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(alfresco_nodes,instance)"
   },
   {
    "name": "core",
    "label": "core",
    "query": "label_values(alfresco_nodes,core)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "expr": "process_uptime_seconds{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=\"$instance\"}*1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"nonheap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{ instance=\"$instance\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{ instance=\"$instance\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{ instance=\"$instance\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{ instance=\"$instance\",area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{ instance=\"$instance\",area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{ instance=\"$instance\",area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Process Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_memory_vss_bytes{instance=\"$instance\"}",
       "legendFormat": "vss"
      },
      {
       "expr": "process_memory_rss_bytes{instance=\"$instance\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{instance=\"$instance\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{instance=\"$instance\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{instance=\"$instance\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{instance=\"$instance\"} + process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{ instance=\"$instance\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{ instance=\"$instance\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{ instance=\"$instance\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{ instance=\"$instance\"}",
       "legendFormat": "system-1m"
      },
      {},
      {
       "expr": "system_cpu_count{ instance=\"$instance\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{instance=\"$instance\",state=\"new\"}",
       "legendFormat": "new"
      },
      {
       "expr": "jvm_threads_states_threads{instance=\"$instance\",state=\"terminated\"}",
       "legendFormat": "terminated"
      },
      {
       "expr": "jvm_threads_states_threads{instance=\"$instance\",state=\"timed-waiting\"}",
       "legendFormat": "timed-waiting"
      },
      {
       "expr": "jvm_threads_states_threads{instance=\"$instance\",state=\"runnable\"}",
       "legendFormat": "runnable"
      },
      {
       "expr": "jvm_threads_states_threads{instance=\"$instance\",state=\"waiting\"}",
       "legendFormat": "waiting"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_files_open_files{ instance=\"$instance\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max_files{ instance=\"$instance\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{ instance=\"$instance\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{instance=\"$instance\"}[5m])",
       "legendFormat": "delta"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{instance=\"$instance\", id=\"direct\"} or jvm_buffer_count_buffers{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{instance=\"$instance\", id=\"mapped\"} or jvm_buffer_count_buffers{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "Solr core stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alfresco_nodes{core=\"$core\",state=\"Indexed\"}",
       "legendFormat": "Nodes"
      },
      {
       "expr": "alfresco_transactions_nodes{core=\"$core\",state=\"Indexed\"}",
       "legendFormat": "Transactions"
      },
      {
       "expr": "alfresco_states{core=\"$core\"}",
       "legendFormat": "States"
      },
      {
       "expr": "alfresco_nodes{core=\"$core\",state=\"Unindexed\"}",
       "legendFormat": "Unindexed nodes"
      },
      {
       "expr": "alfresco_nodes{core=\"$core\",state=\"Error\"}",
       "legendFormat": "Error nodes"
      }
     ]
    },
    {
     "title": "Acls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alfresco_acls{core=\"$core\",state=\"Indexed\"}",
       "legendFormat": "Acls"
      },
      {
       "expr": "alfresco_transactions_acls{core=\"$core\",state=\"Indexed\"}",
       "legendFormat": "Acl transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "Full text search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Full text search status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alfresco_fts{core=\"$core\",state=\"Clean\"}",
       "legendFormat": "Nodes clean (<2.0.0)"
      },
      {
       "expr": "alfresco_fts{core=\"$core\",state=\"Dirty\"}",
       "legendFormat": "Nodes dirty (<2.0.0)"
      },
      {
       "expr": "alfresco_fts{core=\"$core\",state=\"New\"}",
       "legendFormat": "Nodes new (<2.0.0)"
      },
      {
       "expr": "alfresco_fts{core=\"$core\", state=\"InSync\"}",
       "legendFormat": "In sync (>=2.0.0)"
      },
      {
       "expr": "alfresco_fts{core=\"$core\", state=\"ToBeUpdated\"}",
       "legendFormat": "To be update (>=2.0.0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Tracker status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions remaining",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alfresco_transactions_nodes{core=\"$core\",state=\"Remaining\"}",
       "legendFormat": "Approx transactions remaining"
      },
      {
       "expr": "alfresco_transactions_acls{core=\"$core\",state=\"Remaining\"}",
       "legendFormat": "Approx acl transactions remaining"
      }
     ]
    },
    {
     "title": "Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "alfresco_transactions_nodes_lag{core=\"$core\"}",
       "legendFormat": "TX Lag"
      },
      {
       "expr": "alfresco_transactions_acls_lag{core=\"$core\"}",
       "legendFormat": "Acl TX Lag"
      }
     ]
    }
   ]
  },
  { "title": "Searcher stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Searcher warmup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "solr_alfresco_warmupTime{instance=\"$instance\"}",
     "legendFormat": "Warmup time (ms)"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "solr_alfresco_maxDoc{instance=\"$instance\"}",
     "legendFormat": "Max docs"
    },
    {
     "expr": "solr_alfresco_numDocs{instance=\"$instance\"}",
     "legendFormat": "Num docs"
    }
   ]
  },
  {
   "title": "Afts request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_alfresco_15minRateReqsPerSecond{instance=\"$instance\",type=\"/afts\"}",
     "legendFormat": "15 min request rate per second"
    },
    {
     "expr": "solr_alfresco_5minRateReqsPerSecond{instance=\"$instance\",type=\"/afts\"}",
     "legendFormat": "5 min request rate  per second"
    },
    {
     "expr": "solr_alfresco_avgRequestsPerSecond{instance=\"$instance\",type=\"/afts\"}",
     "legendFormat": "Average request rate per second"
    }
   ]
  },
  {
   "title": "Cmis request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_alfresco_15minRateReqsPerSecond{instance=\"$instance\",type=\"/cmis\"}",
     "legendFormat": "15 min request rate "
    },
    {
     "expr": "solr_alfresco_5minRateReqsPerSecond{instance=\"$instance\",type=\"/cmis\"}",
     "legendFormat": "5 min request rate "
    },
    {
     "expr": "solr_alfresco_avgRequestsPerSecond{instance=\"$instance\",type=\"/cmis\"}",
     "legendFormat": "Average request rate"
    }
   ]
  },
  {
   "title": "Afts request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "solr_alfresco_99thPcRequestTime{instance=\"$instance\",type=\"/afts\"}",
     "legendFormat": "99 percentlie request time"
    },
    {
     "expr": "solr_alfresco_95thPcRequestTime{instance=\"$instance\",type=\"/afts\"}",
     "legendFormat": "95 percentlie request time"
    },
    {
     "expr": "solr_alfresco_75thPcRequestTime{instance=\"$instance\",type=\"/afts\"}",
     "legendFormat": "75 percentile request time"
    },
    {
     "expr": "solr_alfresco_avgTimePerRequest{instance=\"$instance\",type=\"/afts\"}",
     "legendFormat": "Average request time"
    }
   ]
  },
  {
   "title": "Cmis request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_alfresco_99thPcRequestTime{instance=\"$instance\",type=\"/cmis\"}",
     "legendFormat": "99 percentlie request time"
    },
    {
     "expr": "solr_alfresco_95thPcRequestTime{instance=\"$instance\",type=\"/cmis\"}",
     "legendFormat": "95 percentlie request time"
    },
    {
     "expr": "solr_alfresco_75thPcRequestTime{instance=\"$instance\",type=\"/cmis\"}",
     "legendFormat": "75 percentlie request time"
    },
    {
     "expr": "solr_alfresco_avgTimePerRequest{instance=\"$instance\",type=\"/cmis\"}",
     "legendFormat": "Average request time"
    }
   ]
  }
 ]
}